apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fc350vysc-go 
  janus-idp.io/tekton: fc350vysc-go
  backstage.io/kubernetes-id: fc350vysc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fc350vysc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml