apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fc350vysc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fc350vysc-go 
  name: fc350vysc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fc350vysc-go 
